name: labcheck

on:
  push:
  pull_request:

jobs:
  labcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Linter unit tests
        run: python -m unittest discover tools -v
      - name: Check the GNS3 project
        run: python tools/labcheck.py gns3/project2_0to255.gns3
